### ISSUE TITLE
Charged Loadstone Invert Sound permanently occupies a sound channel, eher sounds from playingventually blocking all ot

### ISSUE THREAD

**Issue by anonymous123-code** [Gibatron/attraction#5]
Tested Version: Quilt, 1.20.1, only QFAPI

# How to reproduce:
1. Build a setup where a charged loadstone is repeatedly inverted (e.g. pressure plate next to a charged loadstone)
2. Wait until it was inverted about 250 times
4. Observe no other sounds being played (Sometimes the inversion sound itself gets blocked at the end, thats why the time you have to waitmay vary)

# Long explanation.
I suppose that because the sound file has no content, some part of the audio system breaks and it will never stop trying to play it. Howerver, there is a limit how many sounds are playable at the same time. In the end this will block all other sounds from playing. A F3+T fixes it. You can observe the count of sounds playing in the F3 Menu:
![grafik](https://github.com/Gibatron/attraction/assets/61744596/d6aebe45-d730-4853-8778-5d34f69bc4d2)

**Comment by noWickedfortheRest** [comment]
That's a really specific and odd bug. I have no idea how but at some point the sound file was replaced with an empty file. And that means this has been an issue since 1.0... Thanks for tracking it down and providing such a detailed report! 
I just released a new version that adds in the actual sound.
